[package]
name = "binary-trees"
version = "0.1.0"
authors = ["danglotb <bdanglot@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.4.0"
typed-arena = "2.0.1"

[profile.dev]
opt-level = 3
